/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.android.goldeneye.core;

class GoldenEyeJNI {

  static {
    try {
    	//load the library, make sure that libandroid-opencv.so is in your <project>/libs/armeabi directory
    	//so that android sdk automatically installs it along with the app.
        System.loadLibrary("opencv-fr");
    } catch (UnsatisfiedLinkError e) {
    	//badness
    	throw e;
     
    }
  }

  public final static native int convertToGreyScale(String jarg1, String jarg2);
  public final static native int detectFaces(String jarg1, String jarg2, String jarg3);
}
