/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.android.goldeneye.core;

public class GoldenEye {
  public static int convertToGreyScale(String inputImgPath, String greyScaleImgPath) {
    return GoldenEyeJNI.convertToGreyScale(inputImgPath, greyScaleImgPath);
  }

  public static int detectFaces(String inputImgPath, String outputImgPath, String haarClassifierXmlPath) {
    return GoldenEyeJNI.detectFaces(inputImgPath, outputImgPath, haarClassifierXmlPath);
  }

}
